### ISSUE TITLE
UI for generating rules

### ISSUE THREAD

**Issue by onhate** [noolsjs/nools#171]
Hello,

Do you know if there's any UI library for generating nools rules?

**Comment by markbjerke** [comment]
@onhate  
There is the JBoss Drools product which has an extensive UI that runs on the Eclipse platform.  I have never used JBoss Drools but I have studies their documentation to help understand rules engine design.

**Comment by DevSide** [comment]
Yes and there is Drools Workbench which is a product itself based on Drools. It would be more than a feature :smile:
